name: CI/CD

on:
  push:
#     branches: [ master ]

permissions:
  checks: write
  contents: write
  id-token: write
  security-events: write

jobs:
  
  ci:
    name: CI
    uses: ./.github/workflows/ci.yaml
    secrets: inherit

  terraform-cd:
    name: Terraform CD
    needs: ci
    secrets: inherit
    uses: ./.github/workflows/terraform-cd.yaml